server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /opt/savvy/public;
    index index.php;

    client_max_body_size 64M;

    location /build/assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable" always;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
        fastcgi_param HTTPS $https if_not_empty;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto if_not_empty;
        fastcgi_param HTTP_X_FORWARDED_FOR $http_x_forwarded_for if_not_empty;
        fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host if_not_empty;
    }
}
