// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: automation.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteAutomationRule = `-- name: DeleteAutomationRule :exec
DELETE FROM automation_rules WHERE id = ?
`

func (q *Queries) DeleteAutomationRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAutomationRule, id)
	return err
}

const incrementAutomationRuns = `-- name: IncrementAutomationRuns :exec
UPDATE automation_rules SET runs_count = runs_count + 1, last_run_at=?, updated_at=? WHERE id=?
`

type IncrementAutomationRunsParams struct {
	LastRunAt sql.NullString
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) IncrementAutomationRuns(ctx context.Context, arg IncrementAutomationRunsParams) error {
	_, err := q.db.ExecContext(ctx, incrementAutomationRuns, arg.LastRunAt, arg.UpdatedAt, arg.ID)
	return err
}

const insertAutomationLog = `-- name: InsertAutomationLog :exec
INSERT INTO automation_rule_logs (rule_id, trigger_entity_type, trigger_entity_id, actions_executed, status, error_message, created_at)
VALUES (?,?,?,?,?,?,?)
`

type InsertAutomationLogParams struct {
	RuleID            int64
	TriggerEntityType sql.NullString
	TriggerEntityID   sql.NullInt64
	ActionsExecuted   sql.NullString
	Status            string
	ErrorMessage      sql.NullString
	CreatedAt         string
}

func (q *Queries) InsertAutomationLog(ctx context.Context, arg InsertAutomationLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAutomationLog,
		arg.RuleID,
		arg.TriggerEntityType,
		arg.TriggerEntityID,
		arg.ActionsExecuted,
		arg.Status,
		arg.ErrorMessage,
		arg.CreatedAt,
	)
	return err
}

const insertAutomationRule = `-- name: InsertAutomationRule :execresult
INSERT INTO automation_rules (name, description, trigger_type, priority, conditions, actions,
	is_active, stop_processing, created_at, updated_at)
VALUES (?,?,?,?,?,?,?,?,?,?)
`

type InsertAutomationRuleParams struct {
	Name           string
	Description    sql.NullString
	TriggerType    string
	Priority       int64
	Conditions     string
	Actions        string
	IsActive       int64
	StopProcessing int64
	CreatedAt      sql.NullString
	UpdatedAt      sql.NullString
}

func (q *Queries) InsertAutomationRule(ctx context.Context, arg InsertAutomationRuleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertAutomationRule,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.Priority,
		arg.Conditions,
		arg.Actions,
		arg.IsActive,
		arg.StopProcessing,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listAutomationLogs = `-- name: ListAutomationLogs :many
SELECT id, rule_id, trigger_entity_type, trigger_entity_id, actions_executed, status, error_message, created_at
FROM automation_rule_logs WHERE rule_id = ? ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListAutomationLogs(ctx context.Context, ruleID int64) ([]AutomationRuleLog, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationLogs, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationRuleLog{}
	for rows.Next() {
		var i AutomationRuleLog
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.TriggerEntityType,
			&i.TriggerEntityID,
			&i.ActionsExecuted,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationRules = `-- name: ListAutomationRules :many
SELECT id, name, description, trigger_type, priority, conditions, actions,
	is_active, stop_processing, runs_count, last_run_at, created_at, updated_at
FROM automation_rules
WHERE id = COALESCE(?1, id)
  AND is_active = COALESCE(?2, is_active)
  AND trigger_type = COALESCE(?3, trigger_type)
ORDER BY priority, id
`

type ListAutomationRulesParams struct {
	ID          sql.NullInt64
	ActiveOnly  sql.NullInt64
	TriggerType sql.NullString
}

func (q *Queries) ListAutomationRules(ctx context.Context, arg ListAutomationRulesParams) ([]AutomationRule, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationRules, arg.ID, arg.ActiveOnly, arg.TriggerType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationRule{}
	for rows.Next() {
		var i AutomationRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TriggerType,
			&i.Priority,
			&i.Conditions,
			&i.Actions,
			&i.IsActive,
			&i.StopProcessing,
			&i.RunsCount,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAutomationPriority = `-- name: SetAutomationPriority :exec
UPDATE automation_rules SET priority=? WHERE id=?
`

type SetAutomationPriorityParams struct {
	Priority int64
	ID       int64
}

func (q *Queries) SetAutomationPriority(ctx context.Context, arg SetAutomationPriorityParams) error {
	_, err := q.db.ExecContext(ctx, setAutomationPriority, arg.Priority, arg.ID)
	return err
}

const toggleAutomationRule = `-- name: ToggleAutomationRule :exec
UPDATE automation_rules SET is_active=?, updated_at=? WHERE id=?
`

type ToggleAutomationRuleParams struct {
	IsActive  int64
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) ToggleAutomationRule(ctx context.Context, arg ToggleAutomationRuleParams) error {
	_, err := q.db.ExecContext(ctx, toggleAutomationRule, arg.IsActive, arg.UpdatedAt, arg.ID)
	return err
}

const updateAutomationRule = `-- name: UpdateAutomationRule :exec
UPDATE automation_rules SET name=?, description=?, trigger_type=?, priority=?,
	conditions=?, actions=?, is_active=?, stop_processing=?, updated_at=? WHERE id=?
`

type UpdateAutomationRuleParams struct {
	Name           string
	Description    sql.NullString
	TriggerType    string
	Priority       int64
	Conditions     string
	Actions        string
	IsActive       int64
	StopProcessing int64
	UpdatedAt      sql.NullString
	ID             int64
}

func (q *Queries) UpdateAutomationRule(ctx context.Context, arg UpdateAutomationRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateAutomationRule,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.Priority,
		arg.Conditions,
		arg.Actions,
		arg.IsActive,
		arg.StopProcessing,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
