// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backups.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteBackup = `-- name: DeleteBackup :exec
DELETE FROM backups WHERE id = ?
`

func (q *Queries) DeleteBackup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBackup, id)
	return err
}

const getBackup = `-- name: GetBackup :one
SELECT id, filename, size, note, app_version, schema_migrations, created_at
FROM backups WHERE id = ?
`

type GetBackupRow struct {
	ID               int64
	Filename         string
	Size             int64
	Note             sql.NullString
	AppVersion       sql.NullString
	SchemaMigrations sql.NullString
	CreatedAt        sql.NullString
}

func (q *Queries) GetBackup(ctx context.Context, id int64) (GetBackupRow, error) {
	row := q.db.QueryRowContext(ctx, getBackup, id)
	var i GetBackupRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Size,
		&i.Note,
		&i.AppVersion,
		&i.SchemaMigrations,
		&i.CreatedAt,
	)
	return i, err
}

const insertBackup = `-- name: InsertBackup :execresult
INSERT INTO backups (filename, size, note, app_version, created_at, updated_at) VALUES (?,?,?,?,?,?)
`

type InsertBackupParams struct {
	Filename   string
	Size       int64
	Note       sql.NullString
	AppVersion sql.NullString
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
}

func (q *Queries) InsertBackup(ctx context.Context, arg InsertBackupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertBackup,
		arg.Filename,
		arg.Size,
		arg.Note,
		arg.AppVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listBackups = `-- name: ListBackups :many
SELECT id, filename, size, note, app_version, schema_migrations, created_at
FROM backups ORDER BY created_at DESC, id DESC
`

type ListBackupsRow struct {
	ID               int64
	Filename         string
	Size             int64
	Note             sql.NullString
	AppVersion       sql.NullString
	SchemaMigrations sql.NullString
	CreatedAt        sql.NullString
}

func (q *Queries) ListBackups(ctx context.Context) ([]ListBackupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackupsRow{}
	for rows.Next() {
		var i ListBackupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Size,
			&i.Note,
			&i.AppVersion,
			&i.SchemaMigrations,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemaMigrations = `-- name: ListSchemaMigrations :many
SELECT version FROM schema_migrations
`

func (q *Queries) ListSchemaMigrations(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSchemaMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var version string
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
