// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = ?
`

func (q *Queries) DeleteBudget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBudget, id)
	return err
}

const deleteBudgetCategories = `-- name: DeleteBudgetCategories :exec
DELETE FROM budget_category WHERE budget_id = ?
`

func (q *Queries) DeleteBudgetCategories(ctx context.Context, budgetID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBudgetCategories, budgetID)
	return err
}

const deleteBudgetTags = `-- name: DeleteBudgetTags :exec
DELETE FROM budget_tag WHERE budget_id = ?
`

func (q *Queries) DeleteBudgetTags(ctx context.Context, budgetID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBudgetTags, budgetID)
	return err
}

const getGlobalMonthlyBudget = `-- name: GetGlobalMonthlyBudget :one
SELECT b.amount, c.rate, c.is_base FROM budgets b
LEFT JOIN currencies c ON c.id = b.currency_id
WHERE b.is_active = 1 AND b.period = 'monthly' AND b.is_global = 1 LIMIT 1
`

type GetGlobalMonthlyBudgetRow struct {
	Amount float64
	Rate   sql.NullFloat64
	IsBase sql.NullInt64
}

func (q *Queries) GetGlobalMonthlyBudget(ctx context.Context) (GetGlobalMonthlyBudgetRow, error) {
	row := q.db.QueryRowContext(ctx, getGlobalMonthlyBudget)
	var i GetGlobalMonthlyBudgetRow
	err := row.Scan(&i.Amount, &i.Rate, &i.IsBase)
	return i, err
}

const insertBudget = `-- name: InsertBudget :execresult
INSERT INTO budgets (name, amount, currency_id, period, start_date, end_date,
	is_global, notify_at_percent, is_active, created_at, updated_at)
VALUES (?,?,?,?,?,?,?,?,?,?,?)
`

type InsertBudgetParams struct {
	Name            string
	Amount          float64
	CurrencyID      sql.NullInt64
	Period          string
	StartDate       sql.NullString
	EndDate         sql.NullString
	IsGlobal        int64
	NotifyAtPercent sql.NullInt64
	IsActive        int64
	CreatedAt       sql.NullString
	UpdatedAt       sql.NullString
}

func (q *Queries) InsertBudget(ctx context.Context, arg InsertBudgetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertBudget,
		arg.Name,
		arg.Amount,
		arg.CurrencyID,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
		arg.IsGlobal,
		arg.NotifyAtPercent,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertBudgetCategory = `-- name: InsertBudgetCategory :exec
INSERT OR IGNORE INTO budget_category (budget_id, category_id) VALUES (?,?)
`

type InsertBudgetCategoryParams struct {
	BudgetID   int64
	CategoryID int64
}

func (q *Queries) InsertBudgetCategory(ctx context.Context, arg InsertBudgetCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetCategory, arg.BudgetID, arg.CategoryID)
	return err
}

const insertBudgetTag = `-- name: InsertBudgetTag :exec
INSERT OR IGNORE INTO budget_tag (budget_id, tag_id) VALUES (?,?)
`

type InsertBudgetTagParams struct {
	BudgetID int64
	TagID    int64
}

func (q *Queries) InsertBudgetTag(ctx context.Context, arg InsertBudgetTagParams) error {
	_, err := q.db.ExecContext(ctx, insertBudgetTag, arg.BudgetID, arg.TagID)
	return err
}

const listBudgetCategories = `-- name: ListBudgetCategories :many
SELECT c.id, c.name, c.type, c.icon, c.color, 0 AS transactions_count
FROM categories c JOIN budget_category bc ON bc.category_id = c.id
WHERE bc.budget_id = ?
`

type ListBudgetCategoriesRow struct {
	ID                int64
	Name              string
	Type              string
	Icon              sql.NullString
	Color             sql.NullString
	TransactionsCount int64
}

func (q *Queries) ListBudgetCategories(ctx context.Context, budgetID int64) ([]ListBudgetCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetCategories, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetCategoriesRow{}
	for rows.Next() {
		var i ListBudgetCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.Color,
			&i.TransactionsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetTags = `-- name: ListBudgetTags :many
SELECT tags.id, tags.name, tags.created_at, 0 AS transactions_count FROM tags
JOIN budget_tag bt ON bt.tag_id = tags.id WHERE bt.budget_id = ?
`

type ListBudgetTagsRow struct {
	ID                int64
	Name              string
	CreatedAt         sql.NullString
	TransactionsCount int64
}

func (q *Queries) ListBudgetTags(ctx context.Context, budgetID int64) ([]ListBudgetTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetTags, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetTagsRow{}
	for rows.Next() {
		var i ListBudgetTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.TransactionsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgets = `-- name: ListBudgets :many
SELECT b.id, b.name, b.amount, b.currency_id, b.period, b.start_date, b.end_date,
	b.is_global, b.notify_at_percent, b.is_active
FROM budgets b
WHERE b.id = COALESCE(?1, b.id)
ORDER BY b.id
`

type ListBudgetsRow struct {
	ID              int64
	Name            string
	Amount          float64
	CurrencyID      sql.NullInt64
	Period          string
	StartDate       sql.NullString
	EndDate         sql.NullString
	IsGlobal        int64
	NotifyAtPercent sql.NullInt64
	IsActive        int64
}

func (q *Queries) ListBudgets(ctx context.Context, id sql.NullInt64) ([]ListBudgetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBudgets, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsRow{}
	for rows.Next() {
		var i ListBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.CurrencyID,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.IsGlobal,
			&i.NotifyAtPercent,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyBudgets = `-- name: ListMonthlyBudgets :many
SELECT b.amount, c.rate, c.is_base FROM budgets b
LEFT JOIN currencies c ON c.id = b.currency_id
WHERE b.is_active = 1 AND b.period = 'monthly'
`

type ListMonthlyBudgetsRow struct {
	Amount float64
	Rate   sql.NullFloat64
	IsBase sql.NullInt64
}

func (q *Queries) ListMonthlyBudgets(ctx context.Context) ([]ListMonthlyBudgetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMonthlyBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonthlyBudgetsRow{}
	for rows.Next() {
		var i ListMonthlyBudgetsRow
		if err := rows.Scan(&i.Amount, &i.Rate, &i.IsBase); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :exec
UPDATE budgets SET name=?, amount=?, currency_id=?, period=?, start_date=?, end_date=?,
	is_global=?, notify_at_percent=?, is_active=?, updated_at=? WHERE id=?
`

type UpdateBudgetParams struct {
	Name            string
	Amount          float64
	CurrencyID      sql.NullInt64
	Period          string
	StartDate       sql.NullString
	EndDate         sql.NullString
	IsGlobal        int64
	NotifyAtPercent sql.NullInt64
	IsActive        int64
	UpdatedAt       sql.NullString
	ID              int64
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) error {
	_, err := q.db.ExecContext(ctx, updateBudget,
		arg.Name,
		arg.Amount,
		arg.CurrencyID,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
		arg.IsGlobal,
		arg.NotifyAtPercent,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
