// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenges.sql

package sqlc

import (
	"context"
	"database/sql"
)

const consumeTwoFactorChallenge = `-- name: ConsumeTwoFactorChallenge :execresult
UPDATE two_factor_challenges SET consumed_at = ?, updated_at = ?
WHERE token_hash = ? AND consumed_at IS NULL AND expires_at > ?
`

type ConsumeTwoFactorChallengeParams struct {
	ConsumedAt sql.NullString
	UpdatedAt  sql.NullString
	TokenHash  string
	ExpiresAt  string
}

func (q *Queries) ConsumeTwoFactorChallenge(ctx context.Context, arg ConsumeTwoFactorChallengeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, consumeTwoFactorChallenge,
		arg.ConsumedAt,
		arg.UpdatedAt,
		arg.TokenHash,
		arg.ExpiresAt,
	)
}

const countTwoFactorChallenges = `-- name: CountTwoFactorChallenges :one
SELECT COUNT(*) FROM two_factor_challenges
`

func (q *Queries) CountTwoFactorChallenges(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTwoFactorChallenges)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChallengeUserID = `-- name: GetChallengeUserID :one
SELECT user_id FROM two_factor_challenges WHERE token_hash = ?
`

func (q *Queries) GetChallengeUserID(ctx context.Context, tokenHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChallengeUserID, tokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getValidChallengeUserID = `-- name: GetValidChallengeUserID :one
SELECT user_id FROM two_factor_challenges
WHERE token_hash = ? AND consumed_at IS NULL AND expires_at > ?
`

type GetValidChallengeUserIDParams struct {
	TokenHash string
	ExpiresAt string
}

func (q *Queries) GetValidChallengeUserID(ctx context.Context, arg GetValidChallengeUserIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getValidChallengeUserID, arg.TokenHash, arg.ExpiresAt)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const insertTwoFactorChallenge = `-- name: InsertTwoFactorChallenge :exec
INSERT INTO two_factor_challenges (user_id, token_hash, expires_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertTwoFactorChallengeParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

func (q *Queries) InsertTwoFactorChallenge(ctx context.Context, arg InsertTwoFactorChallengeParams) error {
	_, err := q.db.ExecContext(ctx, insertTwoFactorChallenge,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
