// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currencies.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearBaseCurrency = `-- name: ClearBaseCurrency :exec
UPDATE currencies SET is_base = 0 WHERE is_base = 1
`

func (q *Queries) ClearBaseCurrency(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearBaseCurrency)
	return err
}

const countAccountsForCurrency = `-- name: CountAccountsForCurrency :one
SELECT COUNT(*) FROM accounts WHERE currency_id = ?
`

func (q *Queries) CountAccountsForCurrency(ctx context.Context, currencyID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccountsForCurrency, currencyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCurrencies = `-- name: CountCurrencies :one
SELECT COUNT(*) FROM currencies
`

func (q *Queries) CountCurrencies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCurrencies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCurrency = `-- name: DeleteCurrency :exec
DELETE FROM currencies WHERE id = ?
`

func (q *Queries) DeleteCurrency(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCurrency, id)
	return err
}

const getBaseCurrency = `-- name: GetBaseCurrency :one
SELECT id, code, name, symbol, decimals, is_base, rate FROM currencies WHERE is_base = 1 LIMIT 1
`

type GetBaseCurrencyRow struct {
	ID       int64
	Code     string
	Name     string
	Symbol   string
	Decimals int64
	IsBase   int64
	Rate     float64
}

func (q *Queries) GetBaseCurrency(ctx context.Context) (GetBaseCurrencyRow, error) {
	row := q.db.QueryRowContext(ctx, getBaseCurrency)
	var i GetBaseCurrencyRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.IsBase,
		&i.Rate,
	)
	return i, err
}

const getBaseCurrencyCode = `-- name: GetBaseCurrencyCode :one
SELECT code FROM currencies WHERE is_base = 1 LIMIT 1
`

func (q *Queries) GetBaseCurrencyCode(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getBaseCurrencyCode)
	var code string
	err := row.Scan(&code)
	return code, err
}

const getCurrency = `-- name: GetCurrency :one
SELECT id, code, name, symbol, decimals, is_base, rate FROM currencies WHERE id = ?
`

type GetCurrencyRow struct {
	ID       int64
	Code     string
	Name     string
	Symbol   string
	Decimals int64
	IsBase   int64
	Rate     float64
}

func (q *Queries) GetCurrency(ctx context.Context, id int64) (GetCurrencyRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrency, id)
	var i GetCurrencyRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.IsBase,
		&i.Rate,
	)
	return i, err
}

const getCurrencyByCode = `-- name: GetCurrencyByCode :one
SELECT id, code, name, symbol, decimals, is_base, rate FROM currencies WHERE code = ?
`

type GetCurrencyByCodeRow struct {
	ID       int64
	Code     string
	Name     string
	Symbol   string
	Decimals int64
	IsBase   int64
	Rate     float64
}

func (q *Queries) GetCurrencyByCode(ctx context.Context, code string) (GetCurrencyByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyByCode, code)
	var i GetCurrencyByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.IsBase,
		&i.Rate,
	)
	return i, err
}

const insertCurrency = `-- name: InsertCurrency :execresult
INSERT INTO currencies (code, name, symbol, decimals, is_base, rate, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCurrencyParams struct {
	Code      string
	Name      string
	Symbol    string
	Decimals  int64
	IsBase    int64
	Rate      float64
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

func (q *Queries) InsertCurrency(ctx context.Context, arg InsertCurrencyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertCurrency,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.Decimals,
		arg.IsBase,
		arg.Rate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT id, code, name, symbol, decimals, is_base, rate FROM currencies ORDER BY code
`

type ListCurrenciesRow struct {
	ID       int64
	Code     string
	Name     string
	Symbol   string
	Decimals int64
	IsBase   int64
	Rate     float64
}

func (q *Queries) ListCurrencies(ctx context.Context) ([]ListCurrenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrenciesRow{}
	for rows.Next() {
		var i ListCurrenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.Decimals,
			&i.IsBase,
			&i.Rate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrencyCodes = `-- name: ListCurrencyCodes :many
SELECT code FROM currencies
`

func (q *Queries) ListCurrencyCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencyCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOtherCurrencyRates = `-- name: ListOtherCurrencyRates :many
SELECT id, rate FROM currencies WHERE id != ?
`

type ListOtherCurrencyRatesRow struct {
	ID   int64
	Rate float64
}

func (q *Queries) ListOtherCurrencyRates(ctx context.Context, id int64) ([]ListOtherCurrencyRatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOtherCurrencyRates, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOtherCurrencyRatesRow{}
	for rows.Next() {
		var i ListOtherCurrencyRatesRow
		if err := rows.Scan(&i.ID, &i.Rate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrencyBase = `-- name: SetCurrencyBase :exec
UPDATE currencies SET is_base = 1, rate = 1, updated_at = ? WHERE id = ?
`

type SetCurrencyBaseParams struct {
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) SetCurrencyBase(ctx context.Context, arg SetCurrencyBaseParams) error {
	_, err := q.db.ExecContext(ctx, setCurrencyBase, arg.UpdatedAt, arg.ID)
	return err
}

const updateCurrency = `-- name: UpdateCurrency :exec
UPDATE currencies SET name=?, symbol=?, decimals=?, is_base=?, rate=?, updated_at=? WHERE id=?
`

type UpdateCurrencyParams struct {
	Name      string
	Symbol    string
	Decimals  int64
	IsBase    int64
	Rate      float64
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrency,
		arg.Name,
		arg.Symbol,
		arg.Decimals,
		arg.IsBase,
		arg.Rate,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateCurrencyRate = `-- name: UpdateCurrencyRate :exec
UPDATE currencies SET rate = ?, is_base = 0 WHERE id = ?
`

type UpdateCurrencyRateParams struct {
	Rate float64
	ID   int64
}

func (q *Queries) UpdateCurrencyRate(ctx context.Context, arg UpdateCurrencyRateParams) error {
	_, err := q.db.ExecContext(ctx, updateCurrencyRate, arg.Rate, arg.ID)
	return err
}
