// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: imports.sql

package sqlc

import (
	"context"
	"database/sql"
)

const failImport = `-- name: FailImport :exec
UPDATE transaction_imports SET status='failed', message=?, updated_at=? WHERE id=?
`

type FailImportParams struct {
	Message   sql.NullString
	UpdatedAt sql.NullString
	ID        string
}

func (q *Queries) FailImport(ctx context.Context, arg FailImportParams) error {
	_, err := q.db.ExecContext(ctx, failImport, arg.Message, arg.UpdatedAt, arg.ID)
	return err
}

const getImport = `-- name: GetImport :one
SELECT id, user_id, upload_id, status, mapping, options, total_rows, processed_rows,
	created_count, skipped_count, error_count, errors, meta, message
FROM transaction_imports WHERE id = ?
`

type GetImportRow struct {
	ID            string
	UserID        sql.NullInt64
	UploadID      sql.NullString
	Status        string
	Mapping       sql.NullString
	Options       sql.NullString
	TotalRows     sql.NullInt64
	ProcessedRows int64
	CreatedCount  int64
	SkippedCount  int64
	ErrorCount    int64
	Errors        sql.NullString
	Meta          sql.NullString
	Message       sql.NullString
}

func (q *Queries) GetImport(ctx context.Context, id string) (GetImportRow, error) {
	row := q.db.QueryRowContext(ctx, getImport, id)
	var i GetImportRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UploadID,
		&i.Status,
		&i.Mapping,
		&i.Options,
		&i.TotalRows,
		&i.ProcessedRows,
		&i.CreatedCount,
		&i.SkippedCount,
		&i.ErrorCount,
		&i.Errors,
		&i.Meta,
		&i.Message,
	)
	return i, err
}

const importCountsByStatus = `-- name: ImportCountsByStatus :many
SELECT status, COUNT(*) FROM transaction_imports GROUP BY status
`

type ImportCountsByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) ImportCountsByStatus(ctx context.Context) ([]ImportCountsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, importCountsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportCountsByStatusRow{}
	for rows.Next() {
		var i ImportCountsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertImport = `-- name: InsertImport :exec
INSERT INTO transaction_imports (id, user_id, upload_id, status, created_at, updated_at)
VALUES (?,?,?,?,?,?)
`

type InsertImportParams struct {
	ID        string
	UserID    sql.NullInt64
	UploadID  sql.NullString
	Status    string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

func (q *Queries) InsertImport(ctx context.Context, arg InsertImportParams) error {
	_, err := q.db.ExecContext(ctx, insertImport,
		arg.ID,
		arg.UserID,
		arg.UploadID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const markImportCompleted = `-- name: MarkImportCompleted :exec
UPDATE transaction_imports SET status='completed', processed_rows=?, created_count=?, skipped_count=?,
	error_count=?, errors=?, meta=?, updated_at=? WHERE id=?
`

type MarkImportCompletedParams struct {
	ProcessedRows int64
	CreatedCount  int64
	SkippedCount  int64
	ErrorCount    int64
	Errors        sql.NullString
	Meta          sql.NullString
	UpdatedAt     sql.NullString
	ID            string
}

func (q *Queries) MarkImportCompleted(ctx context.Context, arg MarkImportCompletedParams) error {
	_, err := q.db.ExecContext(ctx, markImportCompleted,
		arg.ProcessedRows,
		arg.CreatedCount,
		arg.SkippedCount,
		arg.ErrorCount,
		arg.Errors,
		arg.Meta,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const markImportImporting = `-- name: MarkImportImporting :exec
UPDATE transaction_imports SET status='importing', mapping=?, options=?, processed_rows=0,
	created_count=0, skipped_count=0, error_count=0, errors=NULL, message=NULL, updated_at=? WHERE id=?
`

type MarkImportImportingParams struct {
	Mapping   sql.NullString
	Options   sql.NullString
	UpdatedAt sql.NullString
	ID        string
}

func (q *Queries) MarkImportImporting(ctx context.Context, arg MarkImportImportingParams) error {
	_, err := q.db.ExecContext(ctx, markImportImporting,
		arg.Mapping,
		arg.Options,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const markImportParsed = `-- name: MarkImportParsed :exec
UPDATE transaction_imports SET status='parsed', total_rows=?, meta=?, updated_at=? WHERE id=?
`

type MarkImportParsedParams struct {
	TotalRows sql.NullInt64
	Meta      sql.NullString
	UpdatedAt sql.NullString
	ID        string
}

func (q *Queries) MarkImportParsed(ctx context.Context, arg MarkImportParsedParams) error {
	_, err := q.db.ExecContext(ctx, markImportParsed,
		arg.TotalRows,
		arg.Meta,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
