// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Account struct {
	ID              int64
	Name            string
	Type            string
	DebtType        sql.NullString
	CurrencyID      int64
	InitialBalance  float64
	TargetAmount    sql.NullFloat64
	DueDate         sql.NullString
	IsPaidOff       int64
	Counterparty    sql.NullString
	DebtDescription sql.NullString
	IsActive        int64
	SortOrder       int64
	CreatedAt       sql.NullString
	UpdatedAt       sql.NullString
}

type AuthSession struct {
	ID                int64
	UserID            int64
	TokenHash         string
	Csrf              string
	Ip                sql.NullString
	UserAgent         sql.NullString
	RememberMe        int64
	LastUsedAt        string
	RefreshedAt       sql.NullString
	IdleExpiresAt     string
	AbsoluteExpiresAt string
	RevokedAt         sql.NullString
	CreatedAt         sql.NullString
	UpdatedAt         sql.NullString
}

type AutomationRule struct {
	ID             int64
	Name           string
	Description    sql.NullString
	TriggerType    string
	Priority       int64
	Conditions     string
	Actions        string
	IsActive       int64
	StopProcessing int64
	RunsCount      int64
	LastRunAt      sql.NullString
	CreatedAt      sql.NullString
	UpdatedAt      sql.NullString
}

type AutomationRuleLog struct {
	ID                int64
	RuleID            int64
	TriggerEntityType sql.NullString
	TriggerEntityID   sql.NullInt64
	ActionsExecuted   sql.NullString
	Status            string
	ErrorMessage      sql.NullString
	CreatedAt         string
}

type Backup struct {
	ID               int64
	Filename         string
	Size             int64
	Note             sql.NullString
	AppVersion       sql.NullString
	SchemaMigrations sql.NullString
	CreatedAt        sql.NullString
	UpdatedAt        sql.NullString
}

type Budget struct {
	ID              int64
	Name            string
	Amount          float64
	CurrencyID      sql.NullInt64
	Period          string
	StartDate       sql.NullString
	EndDate         sql.NullString
	IsGlobal        int64
	NotifyAtPercent sql.NullInt64
	IsActive        int64
	CreatedAt       sql.NullString
	UpdatedAt       sql.NullString
}

type BudgetCategory struct {
	BudgetID   int64
	CategoryID int64
}

type BudgetTag struct {
	BudgetID int64
	TagID    int64
}

type Category struct {
	ID        int64
	Name      string
	Type      string
	Icon      sql.NullString
	Color     sql.NullString
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

type Currency struct {
	ID        int64
	Code      string
	Name      string
	Symbol    string
	Decimals  int64
	IsBase    int64
	Rate      float64
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

type IdentityProvider struct {
	ID              int64
	Name            string
	Slug            string
	Protocol        string
	Preset          string
	Enabled         int64
	SortOrder       int64
	Config          sql.NullString
	Secrets         sql.NullString
	ClaimMappings   sql.NullString
	RoleMapping     sql.NullString
	DefaultRole     string
	AllowJit        int64
	SyncRoleOnLogin int64
	LinkByEmail     int64
	CreatedAt       sql.NullString
	UpdatedAt       sql.NullString
}

type PasswordToken struct {
	ID         int64
	UserID     int64
	TokenHash  string
	ExpiresAt  string
	ConsumedAt sql.NullString
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
}

type RecurringTransaction struct {
	ID          int64
	Type        string
	AccountID   int64
	ToAccountID sql.NullInt64
	CategoryID  sql.NullInt64
	Amount      float64
	ToAmount    sql.NullFloat64
	Description sql.NullString
	Frequency   string
	Interval    int64
	DayOfWeek   sql.NullInt64
	DayOfMonth  sql.NullInt64
	StartDate   string
	EndDate     sql.NullString
	NextRunDate string
	LastRunDate sql.NullString
	IsActive    int64
	CreatedAt   sql.NullString
	UpdatedAt   sql.NullString
}

type RecurringTransactionTag struct {
	RecurringTransactionID int64
	TagID                  int64
}

type SchemaMigration struct {
	Version   string
	AppliedAt string
}

type Setting struct {
	Key   string
	Value sql.NullString
}

type SsoLoginState struct {
	ID                 int64
	State              string
	IdentityProviderID int64
	Nonce              sql.NullString
	CodeVerifier       sql.NullString
	SamlRequestID      sql.NullString
	RedirectAfter      sql.NullString
	ExpiresAt          string
	CreatedAt          sql.NullString
	UpdatedAt          sql.NullString
}

type SsoLoginTicket struct {
	ID             int64
	Ticket         string
	UserID         int64
	Requires2fa    int64
	TwoFactorToken sql.NullString
	ExpiresAt      string
	ConsumedAt     sql.NullString
	CreatedAt      sql.NullString
	UpdatedAt      sql.NullString
}

type Tag struct {
	ID        int64
	Name      string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

type Transaction struct {
	ID                     int64
	Type                   string
	AccountID              int64
	ToAccountID            sql.NullInt64
	CategoryID             sql.NullInt64
	Amount                 float64
	ToAmount               sql.NullFloat64
	ExchangeRate           sql.NullFloat64
	Description            sql.NullString
	DedupHash              sql.NullString
	Date                   sql.NullString
	Status                 string
	RecurringTransactionID sql.NullInt64
	CreatedAt              sql.NullString
	UpdatedAt              sql.NullString
}

type TransactionImport struct {
	ID            string
	UserID        sql.NullInt64
	UploadID      sql.NullString
	Status        string
	Mapping       sql.NullString
	Options       sql.NullString
	TotalRows     sql.NullInt64
	ProcessedRows int64
	CreatedCount  int64
	SkippedCount  int64
	ErrorCount    int64
	Errors        sql.NullString
	Meta          sql.NullString
	Message       sql.NullString
	CreatedAt     sql.NullString
	UpdatedAt     sql.NullString
}

type TransactionItem struct {
	ID            int64
	TransactionID int64
	Name          string
	Quantity      float64
	Unit          sql.NullString
	PricePerUnit  float64
	TotalPrice    float64
	CreatedAt     sql.NullString
	UpdatedAt     sql.NullString
}

type TransactionTag struct {
	TransactionID int64
	TagID         int64
}

type TwoFactorChallenge struct {
	ID         int64
	UserID     int64
	TokenHash  string
	ExpiresAt  string
	ConsumedAt sql.NullString
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
}

type TwoFactorRecoveryCode struct {
	ID        int64
	UserID    int64
	Code      string
	UsedAt    sql.NullString
	CreatedAt sql.NullString
}

type Upload struct {
	ID           string
	UserID       sql.NullInt64
	Bucket       string
	ObjectKey    string
	Disk         string
	Path         sql.NullString
	OriginalName string
	MimeType     sql.NullString
	Size         sql.NullInt64
	PartSize     sql.NullInt64
	TotalParts   sql.NullInt64
	Status       string
	CompletedAt  sql.NullString
	ExpiresAt    sql.NullString
	CreatedAt    sql.NullString
	UpdatedAt    sql.NullString
}

type User struct {
	ID                 int64
	Name               string
	Email              string
	Password           sql.NullString
	Role               string
	IsSsoOnly          int64
	TwoFactorSecret    sql.NullString
	TwoFactorEnabled   int64
	TwoFactorConfirmed int64
	CreatedAt          sql.NullString
	UpdatedAt          sql.NullString
}

type UserIdentity struct {
	ID                 int64
	UserID             int64
	IdentityProviderID int64
	Subject            string
	LastLoginAt        sql.NullString
	Claims             sql.NullString
	CreatedAt          sql.NullString
	UpdatedAt          sql.NullString
}

type WebauthnChallenge struct {
	ID         int64
	UserID     sql.NullInt64
	TokenHash  string
	Type       string
	Options    string
	ExpiresAt  string
	ConsumedAt sql.NullString
	CreatedAt  sql.NullString
	UpdatedAt  sql.NullString
}

type WebauthnCredential struct {
	ID           int64
	UserID       int64
	CredentialID string
	Name         sql.NullString
	Aaguid       sql.NullString
	Record       string
	Transports   sql.NullString
	Counter      int64
	LastUsedAt   sql.NullString
	CreatedAt    sql.NullString
	UpdatedAt    sql.NullString
}
