// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recovery.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT COUNT(*) FROM two_factor_recovery_codes WHERE user_id = ? AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM two_factor_recovery_codes WHERE user_id = ?
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodes, userID)
	return err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO two_factor_recovery_codes (user_id, code, created_at) VALUES (?,?,?)
`

type InsertRecoveryCodeParams struct {
	UserID    int64
	Code      string
	CreatedAt sql.NullString
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertRecoveryCode, arg.UserID, arg.Code, arg.CreatedAt)
	return err
}

const invalidateUnusedRecoveryCodes = `-- name: InvalidateUnusedRecoveryCodes :exec
UPDATE two_factor_recovery_codes SET used_at=? WHERE user_id=? AND used_at IS NULL
`

type InvalidateUnusedRecoveryCodesParams struct {
	UsedAt sql.NullString
	UserID int64
}

func (q *Queries) InvalidateUnusedRecoveryCodes(ctx context.Context, arg InvalidateUnusedRecoveryCodesParams) error {
	_, err := q.db.ExecContext(ctx, invalidateUnusedRecoveryCodes, arg.UsedAt, arg.UserID)
	return err
}

const listUnusedRecoveryCodes = `-- name: ListUnusedRecoveryCodes :many
SELECT id, code FROM two_factor_recovery_codes WHERE user_id = ? AND used_at IS NULL
`

type ListUnusedRecoveryCodesRow struct {
	ID   int64
	Code string
}

func (q *Queries) ListUnusedRecoveryCodes(ctx context.Context, userID int64) ([]ListUnusedRecoveryCodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnusedRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnusedRecoveryCodesRow{}
	for rows.Next() {
		var i ListUnusedRecoveryCodesRow
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :exec
UPDATE two_factor_recovery_codes SET used_at=? WHERE id=?
`

type MarkRecoveryCodeUsedParams struct {
	UsedAt sql.NullString
	ID     int64
}

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, arg MarkRecoveryCodeUsedParams) error {
	_, err := q.db.ExecContext(ctx, markRecoveryCodeUsed, arg.UsedAt, arg.ID)
	return err
}
