// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recurring.sql

package sqlc

import (
	"context"
	"database/sql"
)

const advanceRecurring = `-- name: AdvanceRecurring :exec
UPDATE recurring_transactions SET last_run_date=?, next_run_date=?, updated_at=? WHERE id=?
`

type AdvanceRecurringParams struct {
	LastRunDate sql.NullString
	NextRunDate string
	UpdatedAt   sql.NullString
	ID          int64
}

func (q *Queries) AdvanceRecurring(ctx context.Context, arg AdvanceRecurringParams) error {
	_, err := q.db.ExecContext(ctx, advanceRecurring,
		arg.LastRunDate,
		arg.NextRunDate,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const deletePendingForRecurring = `-- name: DeletePendingForRecurring :exec
DELETE FROM transactions WHERE recurring_transaction_id = ? AND status = 'pending'
`

func (q *Queries) DeletePendingForRecurring(ctx context.Context, recurringTransactionID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deletePendingForRecurring, recurringTransactionID)
	return err
}

const deleteRecurring = `-- name: DeleteRecurring :exec
DELETE FROM recurring_transactions WHERE id = ?
`

func (q *Queries) DeleteRecurring(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecurring, id)
	return err
}

const deleteRecurringTags = `-- name: DeleteRecurringTags :exec
DELETE FROM recurring_transaction_tag WHERE recurring_transaction_id = ?
`

func (q *Queries) DeleteRecurringTags(ctx context.Context, recurringTransactionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecurringTags, recurringTransactionID)
	return err
}

const getPendingRecurringTx = `-- name: GetPendingRecurringTx :one
SELECT id FROM transactions WHERE recurring_transaction_id = ? AND status = 'pending' LIMIT 1
`

func (q *Queries) GetPendingRecurringTx(ctx context.Context, recurringTransactionID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPendingRecurringTx, recurringTransactionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRecurring = `-- name: InsertRecurring :execresult
INSERT INTO recurring_transactions (
	type, account_id, to_account_id, category_id, amount, to_amount, description,
	frequency, interval, day_of_week, day_of_month, start_date, end_date,
	next_run_date, is_active, created_at, updated_at)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertRecurringParams struct {
	Type        string
	AccountID   int64
	ToAccountID sql.NullInt64
	CategoryID  sql.NullInt64
	Amount      float64
	ToAmount    sql.NullFloat64
	Description sql.NullString
	Frequency   string
	Interval    int64
	DayOfWeek   sql.NullInt64
	DayOfMonth  sql.NullInt64
	StartDate   string
	EndDate     sql.NullString
	NextRunDate string
	IsActive    int64
	CreatedAt   sql.NullString
	UpdatedAt   sql.NullString
}

func (q *Queries) InsertRecurring(ctx context.Context, arg InsertRecurringParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertRecurring,
		arg.Type,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.Amount,
		arg.ToAmount,
		arg.Description,
		arg.Frequency,
		arg.Interval,
		arg.DayOfWeek,
		arg.DayOfMonth,
		arg.StartDate,
		arg.EndDate,
		arg.NextRunDate,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertRecurringTag = `-- name: InsertRecurringTag :exec
INSERT OR IGNORE INTO recurring_transaction_tag (recurring_transaction_id, tag_id) VALUES (?,?)
`

type InsertRecurringTagParams struct {
	RecurringTransactionID int64
	TagID                  int64
}

func (q *Queries) InsertRecurringTag(ctx context.Context, arg InsertRecurringTagParams) error {
	_, err := q.db.ExecContext(ctx, insertRecurringTag, arg.RecurringTransactionID, arg.TagID)
	return err
}

const listRecurring = `-- name: ListRecurring :many
SELECT id, type, account_id, to_account_id, category_id, amount, to_amount, description,
	frequency, interval, day_of_week, day_of_month, start_date, end_date,
	next_run_date, last_run_date, is_active
FROM recurring_transactions
WHERE id = COALESCE(?1, id)
  AND is_active = COALESCE(?2, is_active)
ORDER BY next_run_date, id
LIMIT ?4 OFFSET ?3
`

type ListRecurringParams struct {
	ID         sql.NullInt64
	ActiveOnly sql.NullInt64
	Offset     int64
	Limit      int64
}

type ListRecurringRow struct {
	ID          int64
	Type        string
	AccountID   int64
	ToAccountID sql.NullInt64
	CategoryID  sql.NullInt64
	Amount      float64
	ToAmount    sql.NullFloat64
	Description sql.NullString
	Frequency   string
	Interval    int64
	DayOfWeek   sql.NullInt64
	DayOfMonth  sql.NullInt64
	StartDate   string
	EndDate     sql.NullString
	NextRunDate string
	LastRunDate sql.NullString
	IsActive    int64
}

func (q *Queries) ListRecurring(ctx context.Context, arg ListRecurringParams) ([]ListRecurringRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecurring,
		arg.ID,
		arg.ActiveOnly,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringRow{}
	for rows.Next() {
		var i ListRecurringRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AccountID,
			&i.ToAccountID,
			&i.CategoryID,
			&i.Amount,
			&i.ToAmount,
			&i.Description,
			&i.Frequency,
			&i.Interval,
			&i.DayOfWeek,
			&i.DayOfMonth,
			&i.StartDate,
			&i.EndDate,
			&i.NextRunDate,
			&i.LastRunDate,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringTags = `-- name: ListRecurringTags :many
SELECT tags.id, tags.name, tags.created_at, 0 AS transactions_count FROM tags
JOIN recurring_transaction_tag rt ON rt.tag_id = tags.id
WHERE rt.recurring_transaction_id = ?
`

type ListRecurringTagsRow struct {
	ID                int64
	Name              string
	CreatedAt         sql.NullString
	TransactionsCount int64
}

func (q *Queries) ListRecurringTags(ctx context.Context, recurringTransactionID int64) ([]ListRecurringTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringTags, recurringTransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringTagsRow{}
	for rows.Next() {
		var i ListRecurringTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.TransactionsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurring = `-- name: UpdateRecurring :exec
UPDATE recurring_transactions SET type=?, account_id=?, to_account_id=?, category_id=?,
	amount=?, to_amount=?, description=?, frequency=?, interval=?, day_of_week=?,
	day_of_month=?, start_date=?, end_date=?, next_run_date=?, is_active=?, updated_at=?
WHERE id=?
`

type UpdateRecurringParams struct {
	Type        string
	AccountID   int64
	ToAccountID sql.NullInt64
	CategoryID  sql.NullInt64
	Amount      float64
	ToAmount    sql.NullFloat64
	Description sql.NullString
	Frequency   string
	Interval    int64
	DayOfWeek   sql.NullInt64
	DayOfMonth  sql.NullInt64
	StartDate   string
	EndDate     sql.NullString
	NextRunDate string
	IsActive    int64
	UpdatedAt   sql.NullString
	ID          int64
}

func (q *Queries) UpdateRecurring(ctx context.Context, arg UpdateRecurringParams) error {
	_, err := q.db.ExecContext(ctx, updateRecurring,
		arg.Type,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.Amount,
		arg.ToAmount,
		arg.Description,
		arg.Frequency,
		arg.Interval,
		arg.DayOfWeek,
		arg.DayOfMonth,
		arg.StartDate,
		arg.EndDate,
		arg.NextRunDate,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
