// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, csrf, remember_me, last_used_at, refreshed_at,
	idle_expires_at, absolute_expires_at, revoked_at, created_at
FROM auth_sessions WHERE token_hash = ?
`

type GetSessionByTokenHashRow struct {
	ID                int64
	UserID            int64
	TokenHash         string
	Csrf              string
	RememberMe        int64
	LastUsedAt        string
	RefreshedAt       sql.NullString
	IdleExpiresAt     string
	AbsoluteExpiresAt string
	RevokedAt         sql.NullString
	CreatedAt         sql.NullString
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Csrf,
		&i.RememberMe,
		&i.LastUsedAt,
		&i.RefreshedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :execresult
INSERT INTO auth_sessions (
	user_id, token_hash, csrf, ip, user_agent, remember_me,
	last_used_at, refreshed_at, idle_expires_at, absolute_expires_at,
	created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	UserID            int64
	TokenHash         string
	Csrf              string
	Ip                sql.NullString
	UserAgent         sql.NullString
	RememberMe        int64
	LastUsedAt        string
	RefreshedAt       sql.NullString
	IdleExpiresAt     string
	AbsoluteExpiresAt string
	CreatedAt         sql.NullString
	UpdatedAt         sql.NullString
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSession,
		arg.UserID,
		arg.TokenHash,
		arg.Csrf,
		arg.Ip,
		arg.UserAgent,
		arg.RememberMe,
		arg.LastUsedAt,
		arg.RefreshedAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const refreshSession = `-- name: RefreshSession :exec
UPDATE auth_sessions SET token_hash=?, csrf=?, last_used_at=?, refreshed_at=?,
	idle_expires_at=?, absolute_expires_at=?, updated_at=?
WHERE id=?
`

type RefreshSessionParams struct {
	TokenHash         string
	Csrf              string
	LastUsedAt        string
	RefreshedAt       sql.NullString
	IdleExpiresAt     string
	AbsoluteExpiresAt string
	UpdatedAt         sql.NullString
	ID                int64
}

func (q *Queries) RefreshSession(ctx context.Context, arg RefreshSessionParams) error {
	_, err := q.db.ExecContext(ctx, refreshSession,
		arg.TokenHash,
		arg.Csrf,
		arg.LastUsedAt,
		arg.RefreshedAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const revokeOtherSessions = `-- name: RevokeOtherSessions :execresult
UPDATE auth_sessions SET revoked_at = ?, updated_at = ?
WHERE user_id = ? AND id != ? AND revoked_at IS NULL
`

type RevokeOtherSessionsParams struct {
	RevokedAt sql.NullString
	UpdatedAt sql.NullString
	UserID    int64
	ID        int64
}

func (q *Queries) RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeOtherSessions,
		arg.RevokedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.ID,
	)
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions SET revoked_at = ?, updated_at = ? WHERE id = ?
`

type RevokeSessionParams struct {
	RevokedAt sql.NullString
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE auth_sessions SET revoked_at = ?, updated_at = ?
WHERE user_id = ? AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	RevokedAt sql.NullString
	UpdatedAt sql.NullString
	UserID    int64
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.ExecContext(ctx, revokeUserSessions, arg.RevokedAt, arg.UpdatedAt, arg.UserID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE auth_sessions SET last_used_at = ?, idle_expires_at = ?, updated_at = ?
WHERE id = ?
`

type TouchSessionParams struct {
	LastUsedAt    string
	IdleExpiresAt string
	UpdatedAt     sql.NullString
	ID            int64
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession,
		arg.LastUsedAt,
		arg.IdleExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
