// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sso.sql

package sqlc

import (
	"context"
	"database/sql"
)

const attachSAMLRequestID = `-- name: AttachSAMLRequestID :exec
UPDATE sso_login_states SET saml_request_id=? WHERE state=?
`

type AttachSAMLRequestIDParams struct {
	SamlRequestID sql.NullString
	State         string
}

func (q *Queries) AttachSAMLRequestID(ctx context.Context, arg AttachSAMLRequestIDParams) error {
	_, err := q.db.ExecContext(ctx, attachSAMLRequestID, arg.SamlRequestID, arg.State)
	return err
}

const consumeSSOTicket = `-- name: ConsumeSSOTicket :execresult
UPDATE sso_login_tickets SET consumed_at=?, updated_at=?
WHERE ticket=? AND consumed_at IS NULL AND expires_at > ?
`

type ConsumeSSOTicketParams struct {
	ConsumedAt sql.NullString
	UpdatedAt  sql.NullString
	Ticket     string
	ExpiresAt  string
}

func (q *Queries) ConsumeSSOTicket(ctx context.Context, arg ConsumeSSOTicketParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, consumeSSOTicket,
		arg.ConsumedAt,
		arg.UpdatedAt,
		arg.Ticket,
		arg.ExpiresAt,
	)
}

const countEnabledIdentityProviders = `-- name: CountEnabledIdentityProviders :one
SELECT COUNT(*) FROM identity_providers WHERE enabled = 1
`

func (q *Queries) CountEnabledIdentityProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledIdentityProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSSOOnlyOrphans = `-- name: CountSSOOnlyOrphans :one
SELECT COUNT(*) FROM (
  SELECT u.id
  FROM users u
  INNER JOIN user_identities mine
    ON mine.user_id = u.id AND mine.identity_provider_id = ?1
  LEFT JOIN user_identities other
    ON other.user_id = u.id AND other.identity_provider_id <> mine.identity_provider_id
  WHERE u.is_sso_only = 1
  GROUP BY u.id
  HAVING COUNT(other.id) = 0
)
`

// One bind: sqlc sqlite mishandles the same named arg twice in EXISTS/NOT EXISTS.
func (q *Queries) CountSSOOnlyOrphans(ctx context.Context, identityProviderID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSSOOnlyOrphans, identityProviderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteIdentityProvider = `-- name: DeleteIdentityProvider :exec
DELETE FROM identity_providers WHERE id = ?
`

func (q *Queries) DeleteIdentityProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIdentityProvider, id)
	return err
}

const deleteSSOState = `-- name: DeleteSSOState :exec
DELETE FROM sso_login_states WHERE state=?
`

func (q *Queries) DeleteSSOState(ctx context.Context, state string) error {
	_, err := q.db.ExecContext(ctx, deleteSSOState, state)
	return err
}

const getSSOState = `-- name: GetSSOState :one
SELECT identity_provider_id, nonce, code_verifier, saml_request_id, redirect_after, expires_at
FROM sso_login_states WHERE state=?
`

type GetSSOStateRow struct {
	IdentityProviderID int64
	Nonce              sql.NullString
	CodeVerifier       sql.NullString
	SamlRequestID      sql.NullString
	RedirectAfter      sql.NullString
	ExpiresAt          string
}

func (q *Queries) GetSSOState(ctx context.Context, state string) (GetSSOStateRow, error) {
	row := q.db.QueryRowContext(ctx, getSSOState, state)
	var i GetSSOStateRow
	err := row.Scan(
		&i.IdentityProviderID,
		&i.Nonce,
		&i.CodeVerifier,
		&i.SamlRequestID,
		&i.RedirectAfter,
		&i.ExpiresAt,
	)
	return i, err
}

const getSSOTicket = `-- name: GetSSOTicket :one
SELECT user_id, requires_2fa FROM sso_login_tickets WHERE ticket=?
`

type GetSSOTicketRow struct {
	UserID      int64
	Requires2fa int64
}

func (q *Queries) GetSSOTicket(ctx context.Context, ticket string) (GetSSOTicketRow, error) {
	row := q.db.QueryRowContext(ctx, getSSOTicket, ticket)
	var i GetSSOTicketRow
	err := row.Scan(&i.UserID, &i.Requires2fa)
	return i, err
}

const getUserIdentity = `-- name: GetUserIdentity :one
SELECT id, user_id FROM user_identities WHERE identity_provider_id=? AND subject=?
`

type GetUserIdentityParams struct {
	IdentityProviderID int64
	Subject            string
}

type GetUserIdentityRow struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (GetUserIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getUserIdentity, arg.IdentityProviderID, arg.Subject)
	var i GetUserIdentityRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const insertIdentityProvider = `-- name: InsertIdentityProvider :execresult
INSERT INTO identity_providers (name, slug, protocol, preset, enabled, sort_order, config, secrets,
	claim_mappings, role_mapping, default_role, allow_jit, sync_role_on_login, link_by_email, created_at, updated_at)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertIdentityProviderParams struct {
	Name            string
	Slug            string
	Protocol        string
	Preset          string
	Enabled         int64
	SortOrder       int64
	Config          sql.NullString
	Secrets         sql.NullString
	ClaimMappings   sql.NullString
	RoleMapping     sql.NullString
	DefaultRole     string
	AllowJit        int64
	SyncRoleOnLogin int64
	LinkByEmail     int64
	CreatedAt       sql.NullString
	UpdatedAt       sql.NullString
}

func (q *Queries) InsertIdentityProvider(ctx context.Context, arg InsertIdentityProviderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertIdentityProvider,
		arg.Name,
		arg.Slug,
		arg.Protocol,
		arg.Preset,
		arg.Enabled,
		arg.SortOrder,
		arg.Config,
		arg.Secrets,
		arg.ClaimMappings,
		arg.RoleMapping,
		arg.DefaultRole,
		arg.AllowJit,
		arg.SyncRoleOnLogin,
		arg.LinkByEmail,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertSSOState = `-- name: InsertSSOState :exec
INSERT INTO sso_login_states (state, identity_provider_id, nonce, code_verifier, saml_request_id, redirect_after, expires_at, created_at, updated_at)
VALUES (?,?,?,?,?,?,?,?,?)
`

type InsertSSOStateParams struct {
	State              string
	IdentityProviderID int64
	Nonce              sql.NullString
	CodeVerifier       sql.NullString
	SamlRequestID      sql.NullString
	RedirectAfter      sql.NullString
	ExpiresAt          string
	CreatedAt          sql.NullString
	UpdatedAt          sql.NullString
}

func (q *Queries) InsertSSOState(ctx context.Context, arg InsertSSOStateParams) error {
	_, err := q.db.ExecContext(ctx, insertSSOState,
		arg.State,
		arg.IdentityProviderID,
		arg.Nonce,
		arg.CodeVerifier,
		arg.SamlRequestID,
		arg.RedirectAfter,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSSOTicket = `-- name: InsertSSOTicket :exec
INSERT INTO sso_login_tickets (ticket, user_id, requires_2fa, expires_at, created_at, updated_at)
VALUES (?,?,?,?,?,?)
`

type InsertSSOTicketParams struct {
	Ticket      string
	UserID      int64
	Requires2fa int64
	ExpiresAt   string
	CreatedAt   sql.NullString
	UpdatedAt   sql.NullString
}

func (q *Queries) InsertSSOTicket(ctx context.Context, arg InsertSSOTicketParams) error {
	_, err := q.db.ExecContext(ctx, insertSSOTicket,
		arg.Ticket,
		arg.UserID,
		arg.Requires2fa,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertUserIdentity = `-- name: InsertUserIdentity :exec
INSERT INTO user_identities (user_id, identity_provider_id, subject, last_login_at, claims, created_at, updated_at)
VALUES (?,?,?,?,?,?,?)
`

type InsertUserIdentityParams struct {
	UserID             int64
	IdentityProviderID int64
	Subject            string
	LastLoginAt        sql.NullString
	Claims             sql.NullString
	CreatedAt          sql.NullString
	UpdatedAt          sql.NullString
}

func (q *Queries) InsertUserIdentity(ctx context.Context, arg InsertUserIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertUserIdentity,
		arg.UserID,
		arg.IdentityProviderID,
		arg.Subject,
		arg.LastLoginAt,
		arg.Claims,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listIdentityProviders = `-- name: ListIdentityProviders :many
SELECT id, name, slug, protocol, preset, enabled, sort_order, config, secrets,
	claim_mappings, role_mapping, default_role, allow_jit, sync_role_on_login, link_by_email, created_at, updated_at
FROM identity_providers
WHERE id = COALESCE(?1, id)
  AND slug = COALESCE(?2, slug)
  AND CASE WHEN ?3 IS NULL THEN 1 ELSE enabled END = 1
ORDER BY sort_order, id
`

type ListIdentityProvidersParams struct {
	ID          sql.NullInt64
	Slug        sql.NullString
	EnabledOnly interface{}
}

func (q *Queries) ListIdentityProviders(ctx context.Context, arg ListIdentityProvidersParams) ([]IdentityProvider, error) {
	rows, err := q.db.QueryContext(ctx, listIdentityProviders, arg.ID, arg.Slug, arg.EnabledOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityProvider{}
	for rows.Next() {
		var i IdentityProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Protocol,
			&i.Preset,
			&i.Enabled,
			&i.SortOrder,
			&i.Config,
			&i.Secrets,
			&i.ClaimMappings,
			&i.RoleMapping,
			&i.DefaultRole,
			&i.AllowJit,
			&i.SyncRoleOnLogin,
			&i.LinkByEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchUserIdentity = `-- name: TouchUserIdentity :exec
UPDATE user_identities SET last_login_at=?, claims=?, updated_at=? WHERE id=?
`

type TouchUserIdentityParams struct {
	LastLoginAt sql.NullString
	Claims      sql.NullString
	UpdatedAt   sql.NullString
	ID          int64
}

func (q *Queries) TouchUserIdentity(ctx context.Context, arg TouchUserIdentityParams) error {
	_, err := q.db.ExecContext(ctx, touchUserIdentity,
		arg.LastLoginAt,
		arg.Claims,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateIdentityProvider = `-- name: UpdateIdentityProvider :exec
UPDATE identity_providers SET name=?, slug=?, protocol=?, preset=?, enabled=?, sort_order=?, config=?, secrets=?,
	claim_mappings=?, role_mapping=?, default_role=?, allow_jit=?, sync_role_on_login=?, link_by_email=?, updated_at=?
WHERE id=?
`

type UpdateIdentityProviderParams struct {
	Name            string
	Slug            string
	Protocol        string
	Preset          string
	Enabled         int64
	SortOrder       int64
	Config          sql.NullString
	Secrets         sql.NullString
	ClaimMappings   sql.NullString
	RoleMapping     sql.NullString
	DefaultRole     string
	AllowJit        int64
	SyncRoleOnLogin int64
	LinkByEmail     int64
	UpdatedAt       sql.NullString
	ID              int64
}

func (q *Queries) UpdateIdentityProvider(ctx context.Context, arg UpdateIdentityProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateIdentityProvider,
		arg.Name,
		arg.Slug,
		arg.Protocol,
		arg.Preset,
		arg.Enabled,
		arg.SortOrder,
		arg.Config,
		arg.Secrets,
		arg.ClaimMappings,
		arg.RoleMapping,
		arg.DefaultRole,
		arg.AllowJit,
		arg.SyncRoleOnLogin,
		arg.LinkByEmail,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
