// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT tags.id, tags.name, tags.created_at,
	(SELECT COUNT(*) FROM transaction_tag tt WHERE tt.tag_id = tags.id)
FROM tags WHERE tags.id = ?
`

type GetTagRow struct {
	ID        int64
	Name      string
	CreatedAt sql.NullString
	Count     int64
}

func (q *Queries) GetTag(ctx context.Context, id int64) (GetTagRow, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i GetTagRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Count,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :execresult
INSERT INTO tags (name, created_at, updated_at) VALUES (?,?,?)
`

type InsertTagParams struct {
	Name      string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertTag, arg.Name, arg.CreatedAt, arg.UpdatedAt)
}

const listTags = `-- name: ListTags :many
SELECT tags.id, tags.name, tags.created_at,
	(SELECT COUNT(*) FROM transaction_tag tt WHERE tt.tag_id = tags.id)
FROM tags ORDER BY name
`

type ListTagsRow struct {
	ID        int64
	Name      string
	CreatedAt sql.NullString
	Count     int64
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tags SET name=?, updated_at=? WHERE id=?
`

type UpdateTagParams struct {
	Name      string
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.ExecContext(ctx, updateTag, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}
