// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const consumePasswordToken = `-- name: ConsumePasswordToken :execresult
UPDATE password_tokens SET consumed_at = ?, updated_at = ?
WHERE token_hash = ? AND consumed_at IS NULL AND expires_at > ?
`

type ConsumePasswordTokenParams struct {
	ConsumedAt sql.NullString
	UpdatedAt  sql.NullString
	TokenHash  string
	ExpiresAt  string
}

func (q *Queries) ConsumePasswordToken(ctx context.Context, arg ConsumePasswordTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, consumePasswordToken,
		arg.ConsumedAt,
		arg.UpdatedAt,
		arg.TokenHash,
		arg.ExpiresAt,
	)
}

const getPasswordTokenByHash = `-- name: GetPasswordTokenByHash :one
SELECT id, user_id, expires_at FROM password_tokens WHERE token_hash = ?
`

type GetPasswordTokenByHashRow struct {
	ID        int64
	UserID    int64
	ExpiresAt string
}

func (q *Queries) GetPasswordTokenByHash(ctx context.Context, tokenHash string) (GetPasswordTokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordTokenByHash, tokenHash)
	var i GetPasswordTokenByHashRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const getValidPasswordToken = `-- name: GetValidPasswordToken :one
SELECT id, user_id, expires_at FROM password_tokens
WHERE token_hash = ? AND consumed_at IS NULL AND expires_at > ?
`

type GetValidPasswordTokenParams struct {
	TokenHash string
	ExpiresAt string
}

type GetValidPasswordTokenRow struct {
	ID        int64
	UserID    int64
	ExpiresAt string
}

func (q *Queries) GetValidPasswordToken(ctx context.Context, arg GetValidPasswordTokenParams) (GetValidPasswordTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getValidPasswordToken, arg.TokenHash, arg.ExpiresAt)
	var i GetValidPasswordTokenRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const insertPasswordToken = `-- name: InsertPasswordToken :exec
INSERT INTO password_tokens (user_id, token_hash, expires_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertPasswordTokenParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

func (q *Queries) InsertPasswordToken(ctx context.Context, arg InsertPasswordTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertPasswordToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const revokeActivePasswordTokens = `-- name: RevokeActivePasswordTokens :exec
UPDATE password_tokens SET consumed_at = ?, updated_at = ?
WHERE user_id = ? AND consumed_at IS NULL
`

type RevokeActivePasswordTokensParams struct {
	ConsumedAt sql.NullString
	UpdatedAt  sql.NullString
	UserID     int64
}

func (q *Queries) RevokeActivePasswordTokens(ctx context.Context, arg RevokeActivePasswordTokensParams) error {
	_, err := q.db.ExecContext(ctx, revokeActivePasswordTokens, arg.ConsumedAt, arg.UpdatedAt, arg.UserID)
	return err
}
