// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const confirmTransaction = `-- name: ConfirmTransaction :exec
UPDATE transactions SET status='confirmed', date=?, updated_at=? WHERE id=?
`

type ConfirmTransactionParams struct {
	Date      sql.NullString
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) ConfirmTransaction(ctx context.Context, arg ConfirmTransactionParams) error {
	_, err := q.db.ExecContext(ctx, confirmTransaction, arg.Date, arg.UpdatedAt, arg.ID)
	return err
}

const countTransactions = `-- name: CountTransactions :one

SELECT COUNT(*) FROM transactions t
WHERE t.id = COALESCE(?1, t.id)
  AND t.type = COALESCE(?2, t.type)
  AND t.account_id = COALESCE(?3, t.account_id)
  AND IFNULL(t.category_id, -1) = IFNULL(?4, IFNULL(t.category_id, -1))
  AND t.status = COALESCE(?5, t.status)
  AND t.date >= COALESCE(?6, t.date)
  AND t.date <= COALESCE(?7, t.date)
`

type CountTransactionsParams struct {
	ID         sql.NullInt64
	Type       sql.NullString
	AccountID  sql.NullInt64
	CategoryID interface{}
	Status     sql.NullString
	StartDate  sql.NullString
	EndDate    sql.NullString
}

// Optional filters use each narg once (COALESCE/CASE). sqlc sqlite emits ?NNN;
// modernc.org/sqlite counts every '?' so "OR col = ?N" (second use) over-binds.
func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactions,
		arg.ID,
		arg.Type,
		arg.AccountID,
		arg.CategoryID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const deleteTransactionItems = `-- name: DeleteTransactionItems :exec
DELETE FROM transaction_items WHERE transaction_id = ?
`

func (q *Queries) DeleteTransactionItems(ctx context.Context, transactionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionItems, transactionID)
	return err
}

const deleteTransactionTags = `-- name: DeleteTransactionTags :exec
DELETE FROM transaction_tag WHERE transaction_id = ?
`

func (q *Queries) DeleteTransactionTags(ctx context.Context, transactionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionTags, transactionID)
	return err
}

const insertTransaction = `-- name: InsertTransaction :execresult
INSERT INTO transactions (type, account_id, to_account_id, category_id, amount, to_amount, exchange_rate,
	description, date, status, recurring_transaction_id, created_at, updated_at)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertTransactionParams struct {
	Type                   string
	AccountID              int64
	ToAccountID            sql.NullInt64
	CategoryID             sql.NullInt64
	Amount                 float64
	ToAmount               sql.NullFloat64
	ExchangeRate           sql.NullFloat64
	Description            sql.NullString
	Date                   sql.NullString
	Status                 string
	RecurringTransactionID sql.NullInt64
	CreatedAt              sql.NullString
	UpdatedAt              sql.NullString
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertTransaction,
		arg.Type,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.Amount,
		arg.ToAmount,
		arg.ExchangeRate,
		arg.Description,
		arg.Date,
		arg.Status,
		arg.RecurringTransactionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertTransactionIgnoreDup = `-- name: InsertTransactionIgnoreDup :execresult
INSERT OR IGNORE INTO transactions (type, account_id, category_id, amount, description, date, status, dedup_hash, created_at, updated_at)
VALUES (?,?,?,?,?,?,?,?,?,?)
`

type InsertTransactionIgnoreDupParams struct {
	Type        string
	AccountID   int64
	CategoryID  sql.NullInt64
	Amount      float64
	Description sql.NullString
	Date        sql.NullString
	Status      string
	DedupHash   sql.NullString
	CreatedAt   sql.NullString
	UpdatedAt   sql.NullString
}

func (q *Queries) InsertTransactionIgnoreDup(ctx context.Context, arg InsertTransactionIgnoreDupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertTransactionIgnoreDup,
		arg.Type,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.Date,
		arg.Status,
		arg.DedupHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertTransactionItem = `-- name: InsertTransactionItem :exec
INSERT INTO transaction_items (transaction_id, name, quantity, price_per_unit, total_price, created_at, updated_at)
VALUES (?,?,?,?,?,?,?)
`

type InsertTransactionItemParams struct {
	TransactionID int64
	Name          string
	Quantity      float64
	PricePerUnit  float64
	TotalPrice    float64
	CreatedAt     sql.NullString
	UpdatedAt     sql.NullString
}

func (q *Queries) InsertTransactionItem(ctx context.Context, arg InsertTransactionItemParams) error {
	_, err := q.db.ExecContext(ctx, insertTransactionItem,
		arg.TransactionID,
		arg.Name,
		arg.Quantity,
		arg.PricePerUnit,
		arg.TotalPrice,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTransactionTag = `-- name: InsertTransactionTag :exec
INSERT OR IGNORE INTO transaction_tag (transaction_id, tag_id) VALUES (?,?)
`

type InsertTransactionTagParams struct {
	TransactionID int64
	TagID         int64
}

func (q *Queries) InsertTransactionTag(ctx context.Context, arg InsertTransactionTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTransactionTag, arg.TransactionID, arg.TagID)
	return err
}

const listTransactionItems = `-- name: ListTransactionItems :many
SELECT id, name, quantity, price_per_unit, total_price FROM transaction_items WHERE transaction_id = ?
`

type ListTransactionItemsRow struct {
	ID           int64
	Name         string
	Quantity     float64
	PricePerUnit float64
	TotalPrice   float64
}

func (q *Queries) ListTransactionItems(ctx context.Context, transactionID int64) ([]ListTransactionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionItems, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionItemsRow{}
	for rows.Next() {
		var i ListTransactionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Quantity,
			&i.PricePerUnit,
			&i.TotalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionSummaryRows = `-- name: ListTransactionSummaryRows :many
SELECT t.type, t.amount, c.rate, c.is_base
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN currencies c ON c.id = a.currency_id
WHERE t.status = ? AND t.type IN ('income','expense')
`

type ListTransactionSummaryRowsRow struct {
	Type   string
	Amount float64
	Rate   float64
	IsBase int64
}

func (q *Queries) ListTransactionSummaryRows(ctx context.Context, status string) ([]ListTransactionSummaryRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionSummaryRows, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionSummaryRowsRow{}
	for rows.Next() {
		var i ListTransactionSummaryRowsRow
		if err := rows.Scan(
			&i.Type,
			&i.Amount,
			&i.Rate,
			&i.IsBase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionTags = `-- name: ListTransactionTags :many
SELECT tags.id, tags.name, tags.created_at, 0 AS transactions_count FROM tags
JOIN transaction_tag tt ON tt.tag_id = tags.id WHERE tt.transaction_id = ?
`

type ListTransactionTagsRow struct {
	ID                int64
	Name              string
	CreatedAt         sql.NullString
	TransactionsCount int64
}

func (q *Queries) ListTransactionTags(ctx context.Context, transactionID int64) ([]ListTransactionTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionTags, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionTagsRow{}
	for rows.Next() {
		var i ListTransactionTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.TransactionsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.type, t.account_id, t.to_account_id, t.category_id, t.amount, t.to_amount, t.exchange_rate,
	t.description, t.date, t.status, t.recurring_transaction_id, t.created_at
FROM transactions t
WHERE t.id = COALESCE(?1, t.id)
  AND t.type = COALESCE(?2, t.type)
  AND t.account_id = COALESCE(?3, t.account_id)
  AND IFNULL(t.category_id, -1) = IFNULL(?4, IFNULL(t.category_id, -1))
  AND t.status = COALESCE(?5, t.status)
  AND t.date >= COALESCE(?6, t.date)
  AND t.date <= COALESCE(?7, t.date)
ORDER BY t.date DESC, t.id DESC
LIMIT ?9 OFFSET ?8
`

type ListTransactionsParams struct {
	ID         sql.NullInt64
	Type       sql.NullString
	AccountID  sql.NullInt64
	CategoryID interface{}
	Status     sql.NullString
	StartDate  sql.NullString
	EndDate    sql.NullString
	Offset     int64
	Limit      int64
}

type ListTransactionsRow struct {
	ID                     int64
	Type                   string
	AccountID              int64
	ToAccountID            sql.NullInt64
	CategoryID             sql.NullInt64
	Amount                 float64
	ToAmount               sql.NullFloat64
	ExchangeRate           sql.NullFloat64
	Description            sql.NullString
	Date                   sql.NullString
	Status                 string
	RecurringTransactionID sql.NullInt64
	CreatedAt              sql.NullString
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions,
		arg.ID,
		arg.Type,
		arg.AccountID,
		arg.CategoryID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AccountID,
			&i.ToAccountID,
			&i.CategoryID,
			&i.Amount,
			&i.ToAmount,
			&i.ExchangeRate,
			&i.Description,
			&i.Date,
			&i.Status,
			&i.RecurringTransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skipTransaction = `-- name: SkipTransaction :exec
UPDATE transactions SET status='skipped', updated_at=? WHERE id=?
`

type SkipTransactionParams struct {
	UpdatedAt sql.NullString
	ID        int64
}

func (q *Queries) SkipTransaction(ctx context.Context, arg SkipTransactionParams) error {
	_, err := q.db.ExecContext(ctx, skipTransaction, arg.UpdatedAt, arg.ID)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions SET type=?, account_id=?, to_account_id=?, category_id=?, amount=?, to_amount=?,
	exchange_rate=?, description=?, date=?, updated_at=? WHERE id=?
`

type UpdateTransactionParams struct {
	Type         string
	AccountID    int64
	ToAccountID  sql.NullInt64
	CategoryID   sql.NullInt64
	Amount       float64
	ToAmount     sql.NullFloat64
	ExchangeRate sql.NullFloat64
	Description  sql.NullString
	Date         sql.NullString
	UpdatedAt    sql.NullString
	ID           int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransaction,
		arg.Type,
		arg.AccountID,
		arg.ToAccountID,
		arg.CategoryID,
		arg.Amount,
		arg.ToAmount,
		arg.ExchangeRate,
		arg.Description,
		arg.Date,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateTransactionCategory = `-- name: UpdateTransactionCategory :exec
UPDATE transactions SET category_id=?, updated_at=? WHERE id=?
`

type UpdateTransactionCategoryParams struct {
	CategoryID sql.NullInt64
	UpdatedAt  sql.NullString
	ID         int64
}

func (q *Queries) UpdateTransactionCategory(ctx context.Context, arg UpdateTransactionCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionCategory, arg.CategoryID, arg.UpdatedAt, arg.ID)
	return err
}

const updateTransactionDescription = `-- name: UpdateTransactionDescription :exec
UPDATE transactions SET description=?, updated_at=? WHERE id=?
`

type UpdateTransactionDescriptionParams struct {
	Description sql.NullString
	UpdatedAt   sql.NullString
	ID          int64
}

func (q *Queries) UpdateTransactionDescription(ctx context.Context, arg UpdateTransactionDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionDescription, arg.Description, arg.UpdatedAt, arg.ID)
	return err
}
