// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uploads.sql

package sqlc

import (
	"context"
	"database/sql"
)

const completeUpload = `-- name: CompleteUpload :exec
UPDATE uploads SET path=?, total_parts=?, status=?, completed_at=?, updated_at=? WHERE id=?
`

type CompleteUploadParams struct {
	Path        sql.NullString
	TotalParts  sql.NullInt64
	Status      string
	CompletedAt sql.NullString
	UpdatedAt   sql.NullString
	ID          string
}

func (q *Queries) CompleteUpload(ctx context.Context, arg CompleteUploadParams) error {
	_, err := q.db.ExecContext(ctx, completeUpload,
		arg.Path,
		arg.TotalParts,
		arg.Status,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const getUpload = `-- name: GetUpload :one
SELECT id, user_id, bucket, object_key, disk, path, original_name, mime_type, size, part_size, total_parts, status, expires_at
FROM uploads WHERE id = ?
`

type GetUploadRow struct {
	ID           string
	UserID       sql.NullInt64
	Bucket       string
	ObjectKey    string
	Disk         string
	Path         sql.NullString
	OriginalName string
	MimeType     sql.NullString
	Size         sql.NullInt64
	PartSize     sql.NullInt64
	TotalParts   sql.NullInt64
	Status       string
	ExpiresAt    sql.NullString
}

func (q *Queries) GetUpload(ctx context.Context, id string) (GetUploadRow, error) {
	row := q.db.QueryRowContext(ctx, getUpload, id)
	var i GetUploadRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bucket,
		&i.ObjectKey,
		&i.Disk,
		&i.Path,
		&i.OriginalName,
		&i.MimeType,
		&i.Size,
		&i.PartSize,
		&i.TotalParts,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const insertUpload = `-- name: InsertUpload :exec
INSERT INTO uploads (id, user_id, bucket, object_key, disk, original_name, mime_type, size, part_size, total_parts, status, expires_at, created_at, updated_at)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type InsertUploadParams struct {
	ID           string
	UserID       sql.NullInt64
	Bucket       string
	ObjectKey    string
	Disk         string
	OriginalName string
	MimeType     sql.NullString
	Size         sql.NullInt64
	PartSize     sql.NullInt64
	TotalParts   sql.NullInt64
	Status       string
	ExpiresAt    sql.NullString
	CreatedAt    sql.NullString
	UpdatedAt    sql.NullString
}

func (q *Queries) InsertUpload(ctx context.Context, arg InsertUploadParams) error {
	_, err := q.db.ExecContext(ctx, insertUpload,
		arg.ID,
		arg.UserID,
		arg.Bucket,
		arg.ObjectKey,
		arg.Disk,
		arg.OriginalName,
		arg.MimeType,
		arg.Size,
		arg.PartSize,
		arg.TotalParts,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listExpiredPendingUploads = `-- name: ListExpiredPendingUploads :many
SELECT id FROM uploads WHERE status = 'pending' AND expires_at IS NOT NULL AND expires_at < ?
`

func (q *Queries) ListExpiredPendingUploads(ctx context.Context, expiresAt sql.NullString) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredPendingUploads, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUploadStatus = `-- name: SetUploadStatus :exec
UPDATE uploads SET status=?, updated_at=? WHERE id=?
`

type SetUploadStatusParams struct {
	Status    string
	UpdatedAt sql.NullString
	ID        string
}

func (q *Queries) SetUploadStatus(ctx context.Context, arg SetUploadStatusParams) error {
	_, err := q.db.ExecContext(ctx, setUploadStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const uploadUsageByBucket = `-- name: UploadUsageByBucket :many
SELECT bucket, status, COUNT(*), COALESCE(SUM(size), 0)
FROM uploads GROUP BY bucket, status
`

type UploadUsageByBucketRow struct {
	Bucket   string
	Status   string
	Count    int64
	Coalesce interface{}
}

func (q *Queries) UploadUsageByBucket(ctx context.Context) ([]UploadUsageByBucketRow, error) {
	rows, err := q.db.QueryContext(ctx, uploadUsageByBucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadUsageByBucketRow{}
	for rows.Next() {
		var i UploadUsageByBucketRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Status,
			&i.Count,
			&i.Coalesce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
