// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webauthn.sql

package sqlc

import (
	"context"
	"database/sql"
)

const consumeWebAuthnChallenge = `-- name: ConsumeWebAuthnChallenge :exec
UPDATE webauthn_challenges SET consumed_at=?, updated_at=? WHERE token_hash=?
`

type ConsumeWebAuthnChallengeParams struct {
	ConsumedAt sql.NullString
	UpdatedAt  sql.NullString
	TokenHash  string
}

func (q *Queries) ConsumeWebAuthnChallenge(ctx context.Context, arg ConsumeWebAuthnChallengeParams) error {
	_, err := q.db.ExecContext(ctx, consumeWebAuthnChallenge, arg.ConsumedAt, arg.UpdatedAt, arg.TokenHash)
	return err
}

const countWebAuthnCredentials = `-- name: CountWebAuthnCredentials :one
SELECT COUNT(*) FROM webauthn_credentials WHERE user_id=?
`

func (q *Queries) CountWebAuthnCredentials(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebAuthnCredentials, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :execresult
DELETE FROM webauthn_credentials WHERE id=? AND user_id=?
`

type DeleteWebAuthnCredentialParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
}

const getOpenWebAuthnChallenge = `-- name: GetOpenWebAuthnChallenge :one
SELECT user_id, options FROM webauthn_challenges
WHERE token_hash=? AND type=? AND consumed_at IS NULL AND expires_at > ?
`

type GetOpenWebAuthnChallengeParams struct {
	TokenHash string
	Type      string
	ExpiresAt string
}

type GetOpenWebAuthnChallengeRow struct {
	UserID  sql.NullInt64
	Options string
}

func (q *Queries) GetOpenWebAuthnChallenge(ctx context.Context, arg GetOpenWebAuthnChallengeParams) (GetOpenWebAuthnChallengeRow, error) {
	row := q.db.QueryRowContext(ctx, getOpenWebAuthnChallenge, arg.TokenHash, arg.Type, arg.ExpiresAt)
	var i GetOpenWebAuthnChallengeRow
	err := row.Scan(&i.UserID, &i.Options)
	return i, err
}

const getWebAuthnUserIDByCredential = `-- name: GetWebAuthnUserIDByCredential :one
SELECT user_id FROM webauthn_credentials WHERE credential_id=?
`

func (q *Queries) GetWebAuthnUserIDByCredential(ctx context.Context, credentialID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWebAuthnUserIDByCredential, credentialID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const insertWebAuthnChallenge = `-- name: InsertWebAuthnChallenge :exec
INSERT INTO webauthn_challenges (user_id, token_hash, type, options, expires_at, created_at, updated_at)
VALUES (?,?,?,?,?,?,?)
`

type InsertWebAuthnChallengeParams struct {
	UserID    sql.NullInt64
	TokenHash string
	Type      string
	Options   string
	ExpiresAt string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
}

func (q *Queries) InsertWebAuthnChallenge(ctx context.Context, arg InsertWebAuthnChallengeParams) error {
	_, err := q.db.ExecContext(ctx, insertWebAuthnChallenge,
		arg.UserID,
		arg.TokenHash,
		arg.Type,
		arg.Options,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertWebAuthnCredential = `-- name: InsertWebAuthnCredential :execresult
INSERT INTO webauthn_credentials (user_id, credential_id, name, aaguid, record, counter, created_at, updated_at)
VALUES (?,?,?,?,?,?,?,?)
`

type InsertWebAuthnCredentialParams struct {
	UserID       int64
	CredentialID string
	Name         sql.NullString
	Aaguid       sql.NullString
	Record       string
	Counter      int64
	CreatedAt    sql.NullString
	UpdatedAt    sql.NullString
}

func (q *Queries) InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.Name,
		arg.Aaguid,
		arg.Record,
		arg.Counter,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listWebAuthnCredentials = `-- name: ListWebAuthnCredentials :many
SELECT id, name, aaguid, last_used_at, created_at
FROM webauthn_credentials WHERE user_id=? ORDER BY id DESC
`

type ListWebAuthnCredentialsRow struct {
	ID         int64
	Name       sql.NullString
	Aaguid     sql.NullString
	LastUsedAt sql.NullString
	CreatedAt  sql.NullString
}

func (q *Queries) ListWebAuthnCredentials(ctx context.Context, userID int64) ([]ListWebAuthnCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebAuthnCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebAuthnCredentialsRow{}
	for rows.Next() {
		var i ListWebAuthnCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Aaguid,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebAuthnRecords = `-- name: ListWebAuthnRecords :many
SELECT record FROM webauthn_credentials WHERE user_id=?
`

func (q *Queries) ListWebAuthnRecords(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listWebAuthnRecords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var record string
		if err := rows.Scan(&record); err != nil {
			return nil, err
		}
		items = append(items, record)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameWebAuthnCredential = `-- name: RenameWebAuthnCredential :execresult
UPDATE webauthn_credentials SET name=?, updated_at=? WHERE id=? AND user_id=?
`

type RenameWebAuthnCredentialParams struct {
	Name      sql.NullString
	UpdatedAt sql.NullString
	ID        int64
	UserID    int64
}

func (q *Queries) RenameWebAuthnCredential(ctx context.Context, arg RenameWebAuthnCredentialParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, renameWebAuthnCredential,
		arg.Name,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
}

const touchWebAuthnCredential = `-- name: TouchWebAuthnCredential :exec
UPDATE webauthn_credentials SET last_used_at=?, updated_at=? WHERE credential_id=?
`

type TouchWebAuthnCredentialParams struct {
	LastUsedAt   sql.NullString
	UpdatedAt    sql.NullString
	CredentialID string
}

func (q *Queries) TouchWebAuthnCredential(ctx context.Context, arg TouchWebAuthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, touchWebAuthnCredential, arg.LastUsedAt, arg.UpdatedAt, arg.CredentialID)
	return err
}
