package db

import (
	"database/sql"

	"github.com/chiririll/savvy-plus/internal/db/sqlc"
)

// Q returns typed queries for db. Generated by `go generate ./internal/db`.
func Q(sqlDB *sql.DB) *sqlc.Queries {
	return sqlc.New(sqlDB)
}

func NullString(s *string) sql.NullString {
	if s == nil {
		return sql.NullString{}
	}
	return sql.NullString{String: *s, Valid: true}
}

func NullStringVal(s string) sql.NullString {
	if s == "" {
		return sql.NullString{}
	}
	return sql.NullString{String: s, Valid: true}
}

func NullInt64(v *int64) sql.NullInt64 {
	if v == nil {
		return sql.NullInt64{}
	}
	return sql.NullInt64{Int64: *v, Valid: true}
}

// NullInt64If set treats 0 as unset (optional filter IDs).
func NullInt64If(v int64) sql.NullInt64 {
	if v == 0 {
		return sql.NullInt64{}
	}
	return sql.NullInt64{Int64: v, Valid: true}
}

func NullFloat64(v *float64) sql.NullFloat64 {
	if v == nil {
		return sql.NullFloat64{}
	}
	return sql.NullFloat64{Float64: *v, Valid: true}
}

func NullInt(v *int) sql.NullInt64 {
	if v == nil {
		return sql.NullInt64{}
	}
	return sql.NullInt64{Int64: int64(*v), Valid: true}
}

func BoolInt(v bool) int64 {
	if v {
		return 1
	}
	return 0
}

// NS wraps a non-empty timestamp or text value as a valid NullString.
func NS(s string) sql.NullString {
	return sql.NullString{String: s, Valid: true}
}

// NI wraps an id as a valid NullInt64 (for nullable FK columns).
func NI(v int64) sql.NullInt64 {
	return sql.NullInt64{Int64: v, Valid: true}
}

// Flag is 1 when v is true, unset otherwise (sqlc optional filters).
func Flag(v bool) sql.NullInt64 {
	if !v {
		return sql.NullInt64{}
	}
	return sql.NullInt64{Int64: 1, Valid: true}
}

// Narg is an optional text filter: empty means unset (sqlc COALESCE/narg).
func Narg(s string) sql.NullString {
	return NullStringVal(s)
}
